#!/bin/sh
### BEGIN INIT INFO
# Provides:          klipper-config
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:
# Short-Description: Setup printer_data directory and bind mount
### END INIT INFO

WRITABLE=/user-resource
PRINTER_DATA=$WRITABLE/printer_data

case "$1" in
    start)
        # Wait for /user-resource to be mounted
        if ! mountpoint -q $WRITABLE; then
            echo "klipper-config: $WRITABLE not mounted, skipping"
            exit 1
        fi

        # Create directory on persistent partition if first boot
        # and then populate with default configs if they don't already exist
        mkdir -p $PRINTER_DATA/config
        cp -n /etc/klipper/printer.cfg $PRINTER_DATA/config
        cp -n /etc/klipper/macros.cfg $PRINTER_DATA/config
        cp -n /etc/moonraker/moonraker.conf $PRINTER_DATA/config
        cp -n /etc/mainsail/mainsail.cfg $PRINTER_DATA/config
        cp -n /etc/guppyscreen/guppyconfig.json $PRINTER_DATA/config

        # Set up /dev/by-name dir which swupdate expects to have
        ln -s /dev/disk/by-partlabel /dev/by-name
        ;;
    stop)
        exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
